In [350]:
import numpy as np
import pandas as pd
from xarray import DataArray

In [284]:
a = [[0,0,],[0,10,],[10,10,],[10,0],]
b = [[0,0,],[0,10,],[12,12,],[10,0],]
c = [[0,0,],[0,12,],[12,13,],[12,0],]
m = [np.array(x) for x in [a,b,c]]
d = [0,10,20]

In [285]:
def load_table(path = 'table_example.txt'):
    def _load_table(path):
        with open(path, 'r') as file:
            conteudo = file.read().split("-------------------------------")
            # # # print(conteudo[0].split('\n'))

            balizas = list()
            all_knunck = list()
            positions = list()
            aplt = 3
            for x in conteudo[:-1]:
                position = x.split('\n')[aplt - 3].split(':')[-1].replace(',', '.')
                position = float(position)
                x = x.split('\n')[aplt:]
                positions.append(
                    position
                )
                aplt = 5
                nList = list()
                nKunckles = list()
                for position in x[:-1]:
                    temp_2 = position.split()
                    temp = [0., 0.]
                    temp[0] = float(temp_2[0].replace(',', '.'))
                    temp[1] = float(temp_2[1].replace(',', '.'))
                    nList.append([temp[0:2]])
                    if len(temp) == 3:
                        nKunckles.append(True)
                    else:
                        nKunckles.append(False)
                values = np.array(nList, dtype=np.float16)
                nKunckles = np.array(nKunckles, dtype=np.float16)
                balizas.append(
                    values.reshape(-1, 2)
                )
                all_knunck.append(nKunckles.reshape(-1, 1))


        
        return {
            'balizas': np.array(balizas, ),
            'knunck': np.array(all_knunck),
            'position': np.array(positions, dtype=np.float16),
        }
    return _load_table(path)

In [286]:
x = load_table()


In [288]:
# criando por uma perspectiva 0
conc = [np.c_[value,np.zeros(value.shape[0]) + distance]\
        for value,distance in zip(x['balizas'],x['position'])]

In [289]:
conc_reshaped = [x.reshape(-1,3) for x in np.array(conc)]

In [290]:
conc_reshaped_all = np.concatenate(conc_reshaped)

In [291]:
table = pd.DataFrame(conc_reshaped_all,columns = ['largura','altura','distancia'])

In [376]:
conc_reshaped_all

array([[ 0.        ,  0.50878906,  0.        ],
       [ 0.        ,  2.56640625,  0.        ],
       [ 0.48608398,  2.55078125,  0.        ],
       ...,
       [ 0.70507812,  2.265625  , 15.8125    ],
       [ 0.71582031,  2.39453125, 15.8125    ],
       [ 0.72998047,  2.625     , 15.8125    ]])

In [379]:
distances = [x[1] for x in zip(x['balizas'],x['position'])]
polygons  = [x[0] for x in zip(x['balizas'],x['position'])]

In [386]:
lof = list()
for polygon,distance in zip(x['balizas'],x['position']):
    r = pd.Series(polygon[:,1],index = polygon[:,0], name = f'poligono({distance})')
    lof.append(r)

In [391]:
lof[0]

0.000000    0.508789
0.000000    2.566406
0.486084    2.550781
0.705078    2.537109
0.895996    2.519531
1.049805    2.496094
1.175781    2.468750
1.283203    2.435547
1.379883    2.402344
1.411133    2.324219
1.438477    2.244141
1.458984    2.156250
1.468750    2.058594
1.465820    1.946289
1.458008    1.886719
1.444336    1.827148
1.424805    1.767578
1.399414    1.709961
1.367188    1.654297
1.327148    1.601562
1.279297    1.553711
1.224609    1.509766
1.164062    1.467773
1.031250    1.392578
0.817871    1.287109
0.680176    1.214844
0.550781    1.140625
0.433105    1.068359
0.329102    0.997070
0.240967    0.929199
0.165039    0.863770
0.033997    0.738770
0.033997   -0.404053
0.000000   -0.404053
0.000000    0.508789
Name: poligono(0.0), dtype: float16

In [392]:
array = DataArray(conc_reshaped_all, dims = ('poligono','coordenadas'), coords = {
    'coordenadas' : ['largura','altura','distancia']
})

In [393]:
array.sel(coordenadas = 'distancia')

<xarray.DataArray (poligono: 387)>
array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.43847656,  1.43847656,  1.43847656,  1.43847656,  1.43847656,
        1.43847656,  1.43847656,  1.43847656,  1.43847656,  1.43847656,
        1.43847656,  1.43847656,  1.43847656,  1.43847656,  1.43847656,
        1.43847656,  1.43847656,  1.43847656,  1.43847656,  1.43847656,
        1.43847656,  1.43847656,  1.43847656,  1.43847656,  1.43847656,
        1.43847656,  1.43847656,  1.43847656,  1.43847656,  1.43847656,
        1.43847656,  1.43847656,  1.43847656,  1.43847656,  2.875     ,
        2.875     ,  2.875     ,  2.875     ,  2.875     ,  2.875     ,
        2.875     ,  2.875     ,  2.875     ,  2.875     ,  2.875     ,
        2.875     ,  2.875     ,  2.875     ,  2.875     ,  2.875     ,
        2.875     ,  2.875     ,  2.875     ,  2.875     ,  2.875     ,
        2.875     ,  2.875     ,  2.875     ,  2.875     ,  2.875     ,
        2.875     ,  2.875     ,  2.875     ,  2.875     ,  2.875     ,
        2.875     ,  2.875     ,  2.875     ,  2.875     ,  2.875     ,
        4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,
        4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,
        4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,
        4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,
        4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,
        4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,
        4.3125    ,  4.3125    ,  5.75      ,  5.75      ,  5.75      ,
        5.75      ,  5.75      ,  5.75      ,  5.75      ,  5.75      ,
        5.75      ,  5.75      ,  5.75      ,  5.75      ,  5.75      ,
        5.75      ,  5.75      ,  5.75      ,  5.75      ,  5.75      ,
        5.75      ,  5.75      ,  5.75      ,  5.75      ,  5.75      ,
        5.75      ,  5.75      ,  5.75      ,  5.75      ,  5.75      ,
        5.75      ,  5.75      ,  5.75      ,  5.75      ,  5.75      ,
        7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,
        7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,
        7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,
        7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,
        7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,
        7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,
        7.1875    ,  7.1875    ,  7.1875    ,  8.625     ,  8.625     ,
        8.625     ,  8.625     ,  8.625     ,  8.625     ,  8.625     ,
        8.625     ,  8.625     ,  8.625     ,  8.625     ,  8.625     ,
        8.625     ,  8.625     ,  8.625     ,  8.625     ,  8.625     ,
        8.625     ,  8.625     ,  8.625     ,  8.625     ,  8.625     ,
        8.625     ,  8.625     ,  8.625     ,  8.625     ,  8.625     ,
        8.625     ,  8.625     ,  8.625     ,  8.625     ,  8.625     ,
        8.625     , 10.0625    , 10.0625    , 10.0625    , 10.0625    ,
       10.0625    , 10.0625    , 10.0625    , 10.0625    , 10.0625    ,
       10.0625    , 10.0625    , 10.0625    , 10.0625    , 10.0625    ,
       10.0625    , 10.0625    , 10.0625    , 10.0625    , 10.0625    ,
       10.0625    , 10.0625    , 10.0625    , 10.0625    , 10.0625    ,
       10.0625    , 10.0625    , 10.0625    , 10.0625    , 10.0625    ,
       10.0625    , 10.0625    , 10.0625    , 11.5       , 11.5       ,
       11.5       , 11.5       , 11.5       , 11.5       , 11.5       ,
     

In [395]:
array.stack(distancia = 'distancia')

TypeError: 'in <string>' requires string as left operand, not ellipsis

In [369]:
disposable_distances = array.sel(coordenadas = 'distancia').to_series().unique()

In [375]:
array.sel(coordenadas = 'distancia')

<xarray.DataArray (pontos: 387)>
array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.43847656,  1.43847656,  1.43847656,  1.43847656,  1.43847656,
        1.43847656,  1.43847656,  1.43847656,  1.43847656,  1.43847656,
        1.43847656,  1.43847656,  1.43847656,  1.43847656,  1.43847656,
        1.43847656,  1.43847656,  1.43847656,  1.43847656,  1.43847656,
        1.43847656,  1.43847656,  1.43847656,  1.43847656,  1.43847656,
        1.43847656,  1.43847656,  1.43847656,  1.43847656,  1.43847656,
        1.43847656,  1.43847656,  1.43847656,  1.43847656,  2.875     ,
        2.875     ,  2.875     ,  2.875     ,  2.875     ,  2.875     ,
        2.875     ,  2.875     ,  2.875     ,  2.875     ,  2.875     ,
        2.875     ,  2.875     ,  2.875     ,  2.875     ,  2.875     ,
        2.875     ,  2.875     ,  2.875     ,  2.875     ,  2.875     ,
        2.875     ,  2.875     ,  2.875     ,  2.875     ,  2.875     ,
        2.875     ,  2.875     ,  2.875     ,  2.875     ,  2.875     ,
        2.875     ,  2.875     ,  2.875     ,  2.875     ,  2.875     ,
        4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,
        4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,
        4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,
        4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,
        4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,
        4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,  4.3125    ,
        4.3125    ,  4.3125    ,  5.75      ,  5.75      ,  5.75      ,
        5.75      ,  5.75      ,  5.75      ,  5.75      ,  5.75      ,
        5.75      ,  5.75      ,  5.75      ,  5.75      ,  5.75      ,
        5.75      ,  5.75      ,  5.75      ,  5.75      ,  5.75      ,
        5.75      ,  5.75      ,  5.75      ,  5.75      ,  5.75      ,
        5.75      ,  5.75      ,  5.75      ,  5.75      ,  5.75      ,
        5.75      ,  5.75      ,  5.75      ,  5.75      ,  5.75      ,
        7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,
        7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,
        7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,
        7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,
        7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,
        7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,  7.1875    ,
        7.1875    ,  7.1875    ,  7.1875    ,  8.625     ,  8.625     ,
        8.625     ,  8.625     ,  8.625     ,  8.625     ,  8.625     ,
        8.625     ,  8.625     ,  8.625     ,  8.625     ,  8.625     ,
        8.625     ,  8.625     ,  8.625     ,  8.625     ,  8.625     ,
        8.625     ,  8.625     ,  8.625     ,  8.625     ,  8.625     ,
        8.625     ,  8.625     ,  8.625     ,  8.625     ,  8.625     ,
        8.625     ,  8.625     ,  8.625     ,  8.625     ,  8.625     ,
        8.625     , 10.0625    , 10.0625    , 10.0625    , 10.0625    ,
       10.0625    , 10.0625    , 10.0625    , 10.0625    , 10.0625    ,
       10.0625    , 10.0625    , 10.0625    , 10.0625    , 10.0625    ,
       10.0625    , 10.0625    , 10.0625    , 10.0625    , 10.0625    ,
       10.0625    , 10.0625    , 10.0625    , 10.0625    , 10.0625    ,
       10.0625    , 10.0625    , 10.0625    , 10.0625    , 10.0625    ,
       10.0625    , 10.0625    , 10.0625    , 11.5       , 11.5       ,
       11.5       , 11.5       , 11.5       , 11.5       , 11.5       ,
       